### ISSUE TITLE
Conjur OSS quickstart includes TLS termination

### ISSUE THREAD

**Issue by garkler** [cyberark/conjur#1039]
## Aha card
https://cyberark.aha.io/features/AAM-181 (Phase 1)
https://cyberark.aha.io/epics/AAM-E-37 (Full Requirement)

## Objective
Add the nginx deployment as part of the docker compose.

## Technical breakdown
@uCatu has created an OSS quickstart here 
https://github.com/cyberark/conjur-quickstart
and instructions for deploying the docker compose
https://docs-staging.conjur.org/OSS/en/Content/OSS/Installation/DockerCompose.htm?tocpath=Setup%7CServer%20Setup%7C_____1

## Defintion of Done
Validate the quickstart guide and scripts.
- [ ] Can be successfully run without error
- [ ] Is helpful/easy to follow (this will be a judgement call).
- [ ] Deploys a working instance of Conjur with TLS termination.

Please let Yvonne & Boaz know your results via the #documentation channel.

**Comment by uCatu** [comment]
Following section in `docker-compose.yaml` is not required

```
  bot_app:
    image: ellerbrock/alpine-bash-curl-ssl
    container_name: bot_app
    command: tail -F anything
    volumes:
    - ./program.sh:/tmp/program.sh
```
