### ISSUE TITLE
Authn-k8s requires authenticated apps to be in specific "apps" policy

### ISSUE THREAD

**Issue by rafis3** [cyberark/conjur#1189]
## Issue Description
The authn-k8s authenticator requires the applications to be specifically defined under the policy `conjur/authn-k8s/<service_id>/apps`. This behavior does not align with the other authenticators and is somewhat limiting the control for the user.

## Expected Behavior
Applications that get authenticated with authn-k8s should be able to reside anywhere in the policy tree. The authenticator should only require that they have `authenticate` permissions on the authenticator instance `!webservice` resource.

DoD:
- [ ] Applications can reside anywhere in the policy tree
- [ ] The solution is backward compatible i.e. old authenticators can work with new conjur and new authenticators can work with old conjur
- [ ] The Core and Community team is familiar with this solution and its design is available to them

**Comment by izgeri** [comment]
Notes from when I experienced the problem:

I assumed if the layer `conjur/authn-k8s/{AUTHENTICATOR_ID}/apps` had the correct privileges (eg has  `[read, authenticate]` on the authenticator webservice and has `[read, execute]` on the needed secrets) that I could just load a host that’s a member of this layer wherever I want in policy and it could use the k8s authn sidecar:
```
- !host
  id: {APPLICATION_NAMESPACE}/service_account/{APPLICATION_SERVICE_ACCOUNT}
  annotations:
    kubernetes/authentication-container-name: secretless
    kubernetes: "true"

- !grant
  role: !layer conjur/authn-k8s/{AUTHENTICATOR_ID}/apps
  member: !host {APPLICATION_NAMESPACE}/service_account/{APPLICATION_SERVICE_ACCOUNT}
```

I learned yesterday that this is not true, and when I try to authenticate as `host/{APPLICATION_NAMESPACE}/service_account/{APPLICATION_SERVICE_ACCOUNT}` using the authn sidecar the Conjur server processes the request as if I authenticated as `host/conjur/authn-k8s/{AUTHENTICATOR_ID}/app/{APPLICATION_NAMESPACE}/service_account/{APPLICATION_SERVICE_ACCOUNT}`
that is - Conjur automatically prepends the host ID I give the authenticator client with a very specific policy branch ID for that specific authenticator service

this breaks some expectations:
- the host ID I provide the authenticator is the fully qualified ID of the host (it’s actually not)
- membership to the layer with the correct privileges is the only thing that matters (it’s not, the layer needs to be in a very specific policy branch and the host must also be defined in that branch)

in addition, we don’t do much to define a healthy pattern for least privilege for apps that use this authenticator if they are all members of a single layer, and secret access is granted to that layer.
