### ISSUE TITLE
Policy load should fail with annotation duplication

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1262]
### This issue has been resolved by [#21](https://github.com/cyberark/conjur-policy-parser/pull/21)

Connected to #1263

---
## Issue description

In case we load a policy with the same annotation on a resource, the server just takes the second one and doesn’t fail the load. This can surprise customers who put in 2 annotations by accident and the server can choose the one that the didn’t want. 

## Steps to reproduce the issue

Load the following policy:
```
- !host
  id: test-app
  annotations:
    some-annotation: value1
    some-annotation: value2
```

## What's the expected result?

An error is raised that annotation `some-annotation` is appears more than once for the resource.

## What's the actual result?

Policy load succeeds and only the last annotation value is applied.
