### ISSUE TITLE
Azure Authenticator

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur#1266]
### **Feature Overview** 
Many of our customers are using Azure as their main cloud provider. The Azure authenticator can run on Conjur (e.g. provider) to enable an Azure application to authenticate according to Azure properties and get back an access token in order to retrieve secret from our providers.

The application can run only as Azure VM.
Highly Desired
- Azure Functions
- App Service
- VM scale set

The scope of this feature is an POC level for customers. The provider run ONLY outside of Azure  - the solution should not be affected from it.

Applications can be identified using the following attributes:

- Subscription ID* - A subscription is an agreement with Microsoft to use one or more Microsoft cloud platforms or services. more data  found  here. This attribute is mandatory in Azure Authentication.

- Resource Group* - A container that holds related resources for an Azure solution. The resource group includes those resources that you want to manage as a group. You decide which resources belong in a resource group based on what makes the most sense for your organization. See Resource groups. This attribute is mandatory in Azure Authentication.

- Identity: Can be ONE of the following (not mandatory):
     - User-assigned identity - The azure operational persona can define for a VM an assigned identity with a specific name and use this name from outside to identify this VM. It helps in scripting and deployment and so on.
     - System-assigned identity (represented by GUID) - Every VM is given a system assigned identity by Azure FW.

More on User assigned identity and system assigned identity is found here: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

**Out Of Scope**
Authentication of User-assigned identity AND System-assigned identity 
If a host is not defined with mandatory annotations : authn-azure/subscription_id and  authn-azure/resource_group but with other azure annotations the loading of this policy should fail. 

### **Process Diagram**
![system assigned id azure.png](https://images.zenhubusercontent.com/5ce1b1cd1285ef7423fe0582/585a2712-082a-4cbc-a68a-ff44d16b4da0)

![user assigned id azure.png](https://images.zenhubusercontent.com/5ce1b1cd1285ef7423fe0582/eec27d39-ed15-4d09-a57d-732bd24867d2)

## Persona - Conjur Admin 

1. Define a host for an application "test-app" with Azure annotations. 

```
- !policy
  id: the-application
  body:
  - !host
    id: test-app 
    annotations:
      description: Hypertext web server
     authn-azure/subscription-id: mylovelysubscriotion
      authn-azure/resource-group: mybestgroup
      authn-azure/user-assigned-identity: test-app-pipeline
OR
      authn-azure/system-assigned-identity: ie_qWCXhXxt1zIEsu4c7acQVGn4
      # Either user_identity or system_identity 

  - !variable required-var

  - !permit
    role: !host test-app
    privilege: [ read, execute ]
    resource: !variable required-var
```

2. Enable Azure Authenticator
Load policy into Conjur with the definition of an Azure authenticator. 

```
# policy id needs to match the convention `conjur/authn-azure/<service ID>`
- !policy
  id: conjur/authn-azure/prod
  body:
  - !webservice
  - !variable
     id: provider-uri # https://sts.windows.net/TENANT_ID
  - !group apps
 
  - !permit
    role: !group apps
    privilege: [ read, authenticate ]
    resource: !webservice

```
**provider-uri** - the URI of Azure Identity Provider, usually it would https://sts.windows.net/TENANT_ID 
The Conjur Admin add value to the variable provider-uri with the URI of Azure Identity Provider, for example: https://sts.windows.net/TENANT_ID

3. The Conjur Admin assign the test-app to be part of "conjur/authn-azure/prod/apps" group.

4. Use Conjur_authenticator env var to enable Azure authenticator

## Azure operations  
1. Already has Subscription ID.
2. Created resource group beforehand.
3. Create a VM in Azure with user assigned identity or system assigned identity
for example:
```
az vm create --name shaharvm --resource-group shaharrg --generate-ssh-keys --image Debian
# Assign system identity
az vm identity assign -g shaharrg -n shaharvm
{
  "systemAssignedIdentity": "7b39461e-85ad-4a52-8b54-d8e4078b9f00",
  "userAssignedIdentities": {}
}

```
3. The operation persona provide the VM the Conjur properties like Conjur_URL 

## App Developer David & Azure Authenticator Logic
1. Authenticate the application against Azure authenticator (REST API) - 
Fetch the Access token provided by Azure ← exact details will be filled in in design phases.

The Oauth2 call returns the Access Token that will be used as an input to the following REST call
```
vm:~$ curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' -H Metadata:true -s | jq .
{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGcNyaXB0aW9ucy8zMzFiMGNlOC0yNDNmLTRhOTktYmRlMS01Njc2ZTU2ZWQ3OTkvcmVzb3VyY2Vncm91cHMvc2hhaGFycmcvcHJvdmlkZXJzL01pY3Jvc29mdC5Db21wdXRlL3ZpcnR1YWxNYWNoaW5lcy9zaGFoYXJ2bSJ9.Qeqvo9z3Cx5fNs1S_-M93WvP2tsso2nWTJc495HYq_ugjHChCSZ6JGNSeM9wFH4Uo7e-ZxJtT96vQ5xkyS_JKk9kIcHcqVIckRHSeXGuvcJVNaxHwRFpUQuFkGufk4nRDnL2nYVHQQvZr7jDS5zU3uHFap_WrbDqIrnx16MhTOkF1w8wibbkWLKVAaIL2nPmpzUAixJw0q4IhUQipPjUThdNbR-mzUTFgEzmA16V2d7cUQid8Rztp8QeFIwzPt9FnfJ8VhmFjOaqTMq7gAXCQRXgrlSl66ijlba8rEPMh6ugo7pqldm7CsbnShwZOqVX37dGO5JH49mtQTRSFa-Gtg",
  "client_id": "fcece960-a7f8-XXXX-...",
  "expires_in": "28800",
  "expires_on": "1568565797",
  "ext_expires_in": "28800",
  "not_before": "1568536697",
  "resource": "https://management.azure.com/",
  "token_type": "Bearer"
}
```

*Note: please pay attention that if the VM has both system and user assigned identity than the above call is not correct and we need to document how the access token is retrieved.

2. Send an authentication request to DAP using the provided Base64-encoded Access Token. 

```
POST https://<DAP-server-hostname>/authn-azure/<service-id>/<account>/<host-id>/authenticate
Header 
Content-Type: application/x-www-form-urlencoded
Body 
 jwt: "eyJhbGciOiJSUzI1NiIs......uTonCA"


```
During this authentication request, Conjur does the following:

A. Validates the Azure Access Token against the Azure Identity Provider 
B. Extracts the name of host from the Body param
C. Validate Azure attributes of the host definition vs Azure Access token
D. Audits the authentication request.
E. Returns a Conjur access token to the application.

3. Retrieve the permitted secrets the application needs using the Conjur access token.
```
GET /<DAP-server-hostname>/secrets/{account}/{kind}/{identifier}{?version}

header: Conjur access token 
```
If repeated calls are required due to rotation schedules, all the API calls above should be done each time, not just this call.

## Azure SDK 
Provide the developer, David, with Azure SDK to fetch secret by having Conjur\DAP as [SecretClient](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.secrets.secretclient?view=azure-dotnet).

DoD:
- [x] add automation for system assigned identity #1434
