### ISSUE TITLE
Challenge the way authenticators store non-sensitive information

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1312]
At current, we store all information - sensitive and non-sensitive - as variables in the authenticator policy.
For example, in authn-azure the variable `provider-uri` is stored as a variable:
```
- !policy
  id: conjur/authn-azure/prod
  body:
  - !webservice

  - !variable
    id: provider-uri  
      
  - !group apps
  
  - !permit
    role: !group apps
    privilege: [ read, authenticate ]
    resource: !webservice
```

This information is not sensitive. We should consider storing this data as an annotation, as follows:
```
# policy id needs to match the convention `conjur/authn-azure/<service ID>`
- !policy
  id: conjur/authn-azure/prod
  body:
  - !webservice
     annotations:
       provider-uri: <some-value>
      
  - !group apps
  
  - !permit
    role: !group apps
    privilege: [ read, authenticate ]
    resource: !webservice
```

This can improve the UX because adding the provider-uri as a variable in the policy demands later that the admin user populate its value through the CLI. Further, adding it as annotation entry makes it easier to set it as a key-value pair and is therefore more readable.

We currently have it a variable for 2 reasons:
1. This is the way it is already implemented in authn-oidc 
2. In case the value is changed the user needs to load the policy again with a replace flag.

We should challenge if we can change it to annotations.

DOD
- [ ] Challenge leads to a decision
- [ ] This decision is updated in the solution-design with explanation
