### ISSUE TITLE
Conjur is tested with Azure system assigned identities

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1458]
We need to verify that hosts with a system-assigned identity can authenticate with Conjur using the Azure Authenticator. This test can't be automated until we can get the system-assigned identity of our Azure VM template into the Jenkins machine environment.

DoD:
- Test exists for following user:
```
      - !host
        id: no-assigned-identity-app
        annotations:
          authn-azure/subscription-id: {{ AZURE_SUBSCRIPTION_ID }}
          authn-azure/resource-group: {{ AZURE_RESOURCE_GROUP }}
          authn-azure/system-assigned-identity: {{ AZURE_VM_SYSTEM_ASSIGNED_IDENTITY }}
```
