### ISSUE TITLE
Add a tool to generate the policy needed for Azure authn from azure token

### ISSUE THREAD

**Issue by abrahamko** [cyberark/conjur#1497]
Motivation: To use Azure authn one needs to create a policy with specific entities and annotations.
This is complex and error-prone, as mistakes will be indicated only when failing to authenticate.

Solution: Create a tool that gets the Azure token that will be used for authentication and it will respond with the correct policy needed to authenticate with this token using the Azure authn

Example:
Given an Azure token (can be taken from [Conjur Azure Authenticator](https://ca-il-confluence.il.cyber-ark.com/display/rndp/Conjur+Azure+Authenticator#/)) you could use to authenticate using Conjur Azure authn.
You need to update the policy in Conjur in 2 places:
1. Root policy to create the azure authn (e.g. [Azure Authn policy](https://github.com/cyberark/conjur/blob/master/ci/authn-azure/policies/policy.yml)
2. Azure apps policy to grant permissions for specific apps using Azure authn. Can be doe using this template: [Azure apps template](https://github.com/cyberark/conjur/blob/master/ci/authn-azure/policies/azure-hosts.template.yml)

For filling step no. 2 you need to find the appropriate values necessary for filling the template.
Any mistake at filling this step correctly will result in failing to authenticate using azure authn, and will require going to the logs to understand why it failed.

Instead, using the proposed tool, you will supply it with the azure token and will get the policy that, when loaded, is granted to pass authentication using this token.
In other words, it will fill the template correctly based on the values in the token.

We support 2 types of identities, system-assigned and user-assigned.
1. So given this azure token of system-assigned identity:
```
{
  "aud": "https://management.azure.com/",
  "iss": "https://sts.windows.net/e563bb15-dd3b-4532-8364-b8998e8aa7c3/",
  "iat": 1568008103,
  "nbf": 1568008103,
  "exp": 1568037203,
  "aio": "42FgYPCaV/7iVzCf6YyfG3dZuD33AwA=",
  "appid": "fcb70b78-067e-47eb-8a20-d9a7de7767e4",
  "appidacr": "2",
  "idp": "https://sts.windows.net/e563bb15-dd3b-4532-8364-b8998e8aa7c3/",
  "oid": "7b39461e-85ad-4a52-8b54-d8e4078b9f00",
  "sub": "7b39461e-85ad-4a52-8b54-d8e4078b9f00",
  "tid": "e563bb15-dd3b-4532-8364-b8998e8aa7c3",
  "uti": "8TRBDmyURka2Npum6AUhAA",
  "ver": "1.0",
  "xms_mirid": "/subscriptions/331b0ce8-243f-4a99-bde1-5676e56ed799/resourcegroups/shaharrg/providers/Microsoft.Compute/virtualMachines/shaharvm"
}
```
the policy will be:
```
      - !host
        id: no-assigned-identity-app
        annotations:
          authn-azure/subscription-id: 331b0ce8-243f-4a99-bde1-5676e56ed799
          authn-azure/resource-group: shaharrg
          authn-azure/system-assigned-identity: 7b39461e-85ad-4a52-8b54-d8e4078b9f00
```
2. And given this azure token of user-assigned identity:
```
{
  "aud": "https://management.azure.com/",
  "iss": "https://sts.windows.net/e563bb15-dd3b-4532-8364-b8998e8aa7c3/",
  "iat": 1568288152,
  "nbf": 1568288152,
  "exp": 1568317252,
  "aio": "42FgYHjm48OWd+ih6x6t0vfVUuGMAA==",
  "appid": "c39edcb4-e25a-4694-bbbe-af6b3fe81736",
  "appidacr": "2",
  "idp": "https://sts.windows.net/e563bb15-dd3b-4532-8364-b8998e8aa7c3/",
  "oid": "9968c90b-8bd5-42b2-876b-c1cfa1d1c8df",
  "sub": "9968c90b-8bd5-42b2-876b-c1cfa1d1c8df",
  "tid": "e563bb15-dd3b-4532-8364-b8998e8aa7c3",
  "uti": "f4ewOezVAkO2pkUgVeYuAA",
  "ver": "1.0",
  "xms_mirid": "/subscriptions/331b0ce8-243f-4a99-bde1-5676e56ed799/resourcegroups/shaharrg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/shaharusermanagedidentity"
}
```
the policy will be:
```
      - !host
        id: no-assigned-identity-app
        annotations:
          authn-azure/subscription-id: 331b0ce8-243f-4a99-bde1-5676e56ed799
          authn-azure/resource-group: shaharrg
          authn-azure/user-assigned-identity: shaharusermanagedidentity
```

DoD:
- [ ] Addition to quincy tool that gets the Azure token and responds with the correct policy
