### ISSUE TITLE
Policy with special characters fails to load

### ISSUE THREAD

**Issue by jtuttle** [cyberark/conjur#1621]
## Summary
Policy with special characters fails to load.

## Steps to Reproduce (needs to be tested)
1. Start Conjur + CLI with dev scripts
2. load the following policy
```
- &active-variables
  - !variable
    id: AccountWithSpecialCharacters~!@#$%^&(){}[]-+=,Name/password
    annotations:
      cyberark-vault: 'true'
      cyberark-vault/accounts: AutomationVault/safeToSync/AccountWithSpecialCharacters~!@#$%^&(){}[]-+=,Name
  - !variable
    id: AccountWithSpecialCharacters~!@#$%^&(){}[]-+=,Name/username
    annotations:
      cyberark-vault: 'true'
      cyberark-vault/accounts: AutomationVault/safeToSync/AccountWithSpecialCharacters~!@#$%^&(){}[]-+=,Name
  - !variable
    id: AccountWithSpecialCharacters~!@#$%^&(){}[]-+=,Name/address
    annotations:
      cyberark-vault: 'true'
      cyberark-vault/accounts: AutomationVault/safeToSync/AccountWithSpecialCharacters~!@#$%^&(){}[]-+=,Name
```

## Expected Results
200 response

## Actual Results (including error logs, if applicable)
422 response
