### ISSUE TITLE
CIDR Restriction - invalid cidr value

### ISSUE THREAD

**Issue by eranha** [cyberark/conjur#1700]
## Summary
An attempt to load a policy with with an invalid CIDR input results with database error.

## Steps to Reproduce
Load policy
```
- !host
  id: www-01
  owner: !group ops-admin
  annotations:
    description: Hypertext web server
  restricted_to: [172.17.0.3, 10.0.0.0/24]
```

## Expected Results
The input should be validated long before it reaches the data layer and fail fast with a clear and concise error message.

## Actual Results (including error logs, if applicable)
In error log:
```
:InvalidTextRepresentation: ERROR:  invalid cidr value: "192.168.0.16/24"
LINE 1: ...ucumber:host:cidr-test-policy2/test-host1', ARRAY['192.168.0...
                                                             ^
DETAIL:  Value has bits set to right of mask.
:(

```
## Reproducible
   * [x ] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
conjur-appliance:5.0-stable

## Environment setup
Encountered on DAP deployment.
