### ISSUE TITLE
Variable Content Validation

### ISSUE THREAD

**Issue by rafis3** [cyberark/conjur#1922]
## Is your feature request related to a problem? Please describe.

Conjur variables are resources that allow a user or an application to define and store sensitive information.

In many cases, such sensitive information is comprised of multiple pieces that are tightly coupled and together represent a complete object. A few examples:

In order to access a MySQL database, a user needs a username, a password and an address, URL or connection string.
In order to access a REST API exposed by a certain service, a user might need either a username and password, a private key and a public certificate, or a token. In addition, the user will need the server public certificate and its address.
Currently, this is handled by defining multiple variables in Conjur. Each variable contains a single value, such as a username, a password, etc. To bundle these pieces together, we use a naming convention. For example:

```yaml
- !policy
  id: my-policy
  body:
  - &vars
    - !variable mysql-db-creds/password
    - !variable mysql-db-creds/username
    - !variable mysql-db-creds/address
    - !variable mysql-db-creds/port

  - !host my-app
  
  - !permit
    role: !host my-app
    privileges: [ read,execute ]
    resource: *vars
```

### Current Limitations

- Multiple variables cannot be updated together, as a single transaction. This might lead to a momentary inconsistency when for example, a username is updated, the password should probably be updated as well.
- There is no enforcement on the content of a variable, which can lead to unintended invalid content.
- There is no enforcement on the group of variables needed for a certain use case. For example, a database connection requires a username, password, connection URL or address and port. A user could accidentally forget to specify a certain needed variable.

## Describe the solution you would like

The proposed solution is to add the ability to use JSON schemas and link them to variables, for which we want validation of their content. This will allow a single variable to store multiple, related values. While it's already possible today, to store JSON structured information in a variable, this proposed feature adds two added values:

- The JSON structure is validated and enforced. If the input is invalid, the user will get a proper error message and the variable update will be denied.
- The JSON structure will not be encrypted completely, but only the sensitive information. This will allow future search capabilities based on the non sensitive information.

## Additional context

Please see the complete proposal [here](https://github.com/cyberark/conjur/blob/master/design/proposals/variable_schema_validation.md).

If you like it, please vote. If you have any suggestions, please comment in this issue.
