### ISSUE TITLE
Conjur Health screen fails to load when a docker container is started

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#316]
I have the following `docker-compose.yml` file:
```yml
version: '3'
services:
  pg:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur
    command: server -a cucumber -p 3000
    environment:
      CONJUR_APPLIANCE_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_ADMIN_PASSWORD: admin
      CONJUR_PASSWORD_ALICE: secret
      CONJUR_DATA_KEY: "W0BuL8iTr/7QvtjIluJbrb5LDAnmXzmcpxkqihO3dXA="
    ports:
      - "3000:3000"
    networks:
      - default
    links:
      - pg:pg
```

Running `docker-compose up` starts the application as expected.  When I go to `http://localhost:3000`, I see the following error in the log:

```
conjur_1   | LoadError (cannot load such file -- yui/compressor):
conjur_1   |   app/views/layouts/application.html.erb:7:in `_app_views_layouts_application_html_erb__596828223681987448_32307500'
conjur_1   |   app/controllers/status_controller.rb:3:in `index'
conjur_1   |   app/controllers/application_controller.rb:33:in `block in run_with_transaction'
conjur_1   |   app/controllers/application_controller.rb:32:in `run_with_transaction'
```

It looks like we're missing a gem or a library in the build process.  I would expect the health summary page to be viewable the url.
