### ISSUE TITLE
Policy replace can fail when user is deleted and removed from group

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur#489]
If you have a multi-file root policy, and you call `conjur policy load --replace root file1.yml` where file1 references groups not defined in file1, you will get a 500 error.

Fixing this bug will include sending a more useful error response and updating documentation to be more clear about handling multi-file policie.

**Comment by izgeri** [comment]
If I have a policy with a user
```
- !userid: developer1
  owner: !group security-admin
  annotations:
    first_name: Mary
    last_name: Lamb
    email: mary.lamb@company.com
```
that belongs to a group
```
- !grant
  role: !group developers
  members:
    - !user developer1
    - !user developer2
    - !user dev-admin
```
(see [here](https://github.com/izgeri/conjur-policy-demos/tree/master/basic-app-v5))
and I try to remove them from the policy by deleting the `developer1` user and its group membership and reloading with the `--replace` flag (ie `conjur policy load --replace root users.yml`), that gives a 500 error:
`PG::ForeignKeyViolation: ERROR: insert or update on table "role_memberships" violates foreign key constraint "role_memberships_role_id_fkey" DETAIL: Key (role_id)=(cucumber:group:developers) is not present in table "roles".`
The full error page returned is attached.
