### ISSUE TITLE
Multi-Domain LDAP Authentication

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#527]
**Feature Overview**
Many of our customers use Active Directory with multiple domains.  Currently, our integration only supports a single domain.  Enabling multiple domains will let more organizations leverage LDAP for authenticating with Conjur

**Implementation Details**
Each LDAP authenticator will be configured to connect to a specific domain.  Below is a sample LDAP Authenticator policy:
```yml
- !policy
  id: conjur/authn-ldap/test
  body:
  - !webservice
    annotations:
      ldap/uri: ldap://ldap-server:389
      ldap/base: dc=conjur,dc=net
      ldap/filter: '(uid=%s)'
      ldap/bind_dn: cn=admin,dc=conjur,dc=net
      ldap/bind_pw: !variable bind_pw

  # variable to hold the LDAP password for the DN user.
  - !variable bind_pw
  
  # Provide permission to the layer to retrieve the password stored in `!variable bind_pw`
  - !permit
    role: !webservice
    privilege: [ read, authenticate ]
    resource: !variable bind_pw

  - !group clients

  - !permit
    role: !group clients
    privilege: [ read, authenticate ]
    resource: !webservice

- !grant
  role: !group conjur/authn-ldap/test/clients
  member: !group ldap-users
```
