### ISSUE TITLE
Variable Expiration and Rotation

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#544]
**Feature Overview**
Variables in Conjur can be configured to exist for a period of time before they disappear.  This feature becomes most powerful when it's paired with rotation.

**Workflow**
Let's look at a Conjur variable:
```yml
- !variable
      id: database/username
      annotations:
        expiration: 2018-07-28T23:14:04Z
```
