### ISSUE TITLE
OpenID Connect Authenticator

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#546]
**Feature Overview**
The OpenID Connect Authenticator allows an OpenID Connect server to be used to authenticate to Conjur.

**Setup**
To enable an OpenID Connect Authenticator called `prod`, we'll set the following environment variable when we start Conjur:
```
CONJUR_AUTHENTICATORS=authn-openid_connect/prod
```

In this context, `prod` is the called the `service ID`. Multiple authenticators can be configured with different service IDs. Each one implements a separate "zone" of authentication.

After Conjur is started, we'll create a policy to enable our `prod` OpenID Connect Authenticator:

```yml
# policy id needs to match the convention `conjur/authn-openid_connect/<service ID>`
- !policy
  id: conjur/authn-openid_connect/prod
  body:
  - !webservice

  - !group clients
 
  - !permit
    role: !group clients
    privilege: [ read, authenticate ]
    resource: !webservice
```
In order for a user to be able to authenticate using OpenID Connect, we need to provide that user permission to read and authenticate to our webservice:
```yml
- !user jane.smith

- !grant
  role: !group conjur/authn-openid_connect/prod/clients
  member: !user jane.smith
```
**Note**: The username in Conjur must match the user name for OpenID Connect.

Groups of users can also be added:
```yml
- !group developers

- !user jane.smith
- !user fred.jones

- !grant 
  role: !group developers
  members:
    - !user jane.smith
    - !user fred.jones

- !grant
  role: !group conjur/authn-openid_connect/prod/clients
  member: !group developers
```

A user will be able to authenticate with Conjur using their OpenID Connect credentials using the API, CLI, or Summon after setting the `CONJUR_AUTHN_URL` environment variable:
```
CONJUR_AUTHN_URL = https://conjur.company.com/authn-openid_connect/<authenticator-name>/<service-account>/<username>/authenticate
```
The UI can be configured at startup to only allow OpenID Connect authentication, by setting the `CONJUR_AUTHN_URL` on the Conjur appliance.

**Implementation Details**
