### ISSUE TITLE
Authentication Token TTL is configurable

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#596]
As an operator of Conjur, I want to be able to manage the authentication token TTL so that I can set on a per authenticator basis, as makes sense for a particular authenticator. For example, for I may want it to be a longer time for IAM authentication to prevent running into AWS rate limiting.

GIVEN a running Conjur with the following authn-iam policy loaded:
```yml
- !policy
  id: conjur/authn-iam/prod
  body:
  - !webservice
    annotations:
      authn/ttl: PT1H # token valid for 1 hour

  - !group clients
 
  - !permit
    role: !group clients
    privilege: [ read, authenticate ]
    resource: !webservice
```
WHEN a token is receive after successfully authentication
THEN the token is valid for 1 hour
AND if the `authn/ttl` annotation is not present
THEN the token expires as normal (8 minutes)
