### ISSUE TITLE
absolute paths in a  nested policy aren't resolved correctly.

### ISSUE THREAD

**Issue by apotterri** [cyberark/conjur#600]
This policy fails to load as the root policy in the `cucumber` account

```
- !user alice
- !user bob

- !policy
  id: dev
  owner: !user /alice
  body:
  - !policy
    id: db
    owner: !user /bob
```

`/alice` resolves correctly as `cucumber:user:alice`. However, `/bob` resolves to the role `cucumber:user:/bob@dev` rather than `cucumber:user:bob`.
