### ISSUE TITLE
Conjur supports Dynamic Secrets

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#659]
Time estimate: 5 weeks
ETA for completion of this epic: TBD
Confidence level of ETA accuracy: Low

> This feature issue is a **work in progress**

## Overview

Dynamic secrets are credentials created on-demand by Conjur to connect to a third-party service. This is accomplished using pluggable **Credential Factories**. A Credential Factory is a Conjur resource that is annotated configure:

* A credential factory provider to use:
    ```yaml
    credential-factory/provider: aws
    ```
    ```yaml
    credential-factory/provider: postgresql
    ```
* Credentials for the external service to use when creating new dynamic credentials:
    ```yaml
    credential-factory/aws/region: us-east-1
    credential-factory/aws/access-key-id: "23478207027842073230762374023"
    # reference to a Conjur variable
    credential-factory/aws/secret-access-key: aws/dev-account/secret-access-key 
    ```
    ```yaml
    credential-factory/postgresql/user: postgres
    # reference to a Conjur variable
    credential-factory/postgresql/password: psql/dev-account/root-password
    ```

* Service-specific parameters to apply to dynamic credentials when created (e.g. IAM policy, TTL):
    ```yaml
    # Common parameters
    credential-factory/ttl: PT1H # One hour TTL
    ```
    ```yaml
    # Provider specific parameters
    credential-factory/aws/iam-policy: |
        {    
          "Version" : "2012-10-17",   
          "Statement" : [
            {
              "Action" : [           
                "sts:GetCallerIdentity"
              ],           
              "Effect" : "Allow",           
              "Resource" : "*"       
            }
          ]
    ```
    ```yaml
    credential-factory/postgresql/database: postgres
    credential-factory/postgresql/template: |
      CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' 
      VALID UNTIL '{{expiration}}'; 
      GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}";
    ```

Once created, these dynamic secrets are stored in Conjur, and Conjur manages their lifecycle. The lifecycle for a dynamic secret may include:

* **Creation**
  Dynamic secrets are created using the Conjur API

  > COMMENT: It's convenient if this can simply use the `/secrets` endpoint as described in the initial write-up. For managing the lifecycle, we'll need some kind of lifetime identifier. This could be in the form of a conjur variable, or a convention on the factory path (e.g. appending the AWS token id, or PostgreSQL username) to enable renewal or revocation). 

* **Refresh/Renewal**
  It may be desirable to allow a short-lived credential to be renewed, perhaps to a `maximum_ttl`.

* **Revocation**
  Dynamic secrets may be revoked, either through the Conjur API or through properties on the dynamic secret (e.g. expiration).
  > COMMENT: This could probably be handled by rotators as they exist now. There may be a desire to enable "hard" expiration, where the credential is removed, rather than just having its value rotated.

### AWS Access Token

![STS use case](https://user-images.githubusercontent.com/1534633/43587039-3f77daac-9637-11e8-9c4a-ba74ff40a0b5.png)

#### Description

Dynamic secrets for AWS make it simple to issue short-lived, limited scope credentials on-demand for users or services to access cloud resources.

#### Prerequisites 
A credential factory for AWS would need to be initially created with:
1.  Privileged access credentials that can be used to issue new STS tokens
2. IAM policy to attach to the newly created tokens

Example policy for creating an AWS credential factory:
```yaml
- !webservice aws-credentials
  annotations:
    credential-factory/provider: aws
    credential-factory/aws/region: us-east-1
    credential-factory/aws/access-key-id: "23478207027842073230762374023"
    credential-factory/aws/secret-access-key: aws/dev-account/secret-access-key
    credential-factory/aws/iam-policy: |
        {    
          "Version" : "2012-10-17",   
          "Statement" : [
            {
              "Action" : [           
                "sts:GetCallerIdentity"
              ],           
              "Effect" : "Allow",           
              "Resource" : "*"       
            }
          ]
 
- !layer
 
- !permit
  resources: !webservice aws-credentials
  privileges: [ read, execute ]
  role: !layer
```

#### Workflow

1. The **requester** authenticates to Conjur using their user or host credentials

2. The **requestor** then asks the AWS credential factory for a new AWS access token
    ```
    GET https://conjur.myorg.net/secrets/cucumber/webservice/aws
   ```

3. The Conjur credential factory authenticates to AWS using the configured credentials and uses the AWS API to create a new access token with the configured policy.

4. AWS returns the token to the credential factory, which will then store it in Conjur

5. The credential factory will return the token to the **requester**
    ```
    {
        "id": "cucumber:variable:cucumber/webservice/aws/ASIAI6...F7KPBKA",
        "token": "{ \"access_key_id\": \"ASIAI6...F7KPBKA\", \"secret_access_key\": \"EhyQYceI...arRtkZfYugB9dDM6\",  \"session_token\": \"FQoDYXdzEH4aD...7bz7Nw+NL0mKNr8ztYF\",  \"expiration\": \"2018-04-15 22:04:26 UTC\",  \"federated_user_id\": \"<acct-id>:myapp\", \"federated_user_arn\": \"arn:aws:sts::<acct-id>:federated-user\/myapp\"}"
    }
    ```

    > COMMENT: Alternatively, the id could be provided as a response header

6. The **requester** uses the token to connect to AWS (e.g. to create an EC2 instance)

7. Conjur will revoke the token when either the TTL elapses, or when requested through the Conjur API

### Postgres Database Access

![postgres use case](https://user-images.githubusercontent.com/1534633/43586524-d9beb72c-9635-11e8-9a62-cbcfb65f618c.png)

#### Description

Dynamic secrets for PostgreSQL make it possible to issue short-lived, limited scope credentials on-demand for users or services to access a PostgreSQL database.

#### Prerequisites 
A credential factory for PostgreSQL would need to be initially created with:
1.  Privileged access credentials that can be used to create new database users
2. PostgreSQL in which to create dynamic users
3. (Optional) `CREATE` template for customizing the user creation.

Example policy for creating a PostgreSQL credential factory:
> Implementation Note: Named create templates (e.g. `read`, `read_and_write`) could be provided to make it easier to specify alternative behavior for security personas, as well as make them more reusable.

```yaml
- !webservice psql-credentials
  annotations:
    credential-factory/provider: postgresql
    credential-factory/postgresql/user: postgres
    credential-factory/postgresql/password: psql/dev-account/root-password
    credential-factory/postgresql/database: app-db-dev
    credential-factory/postgresql/template: |
      CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' 
      VALID UNTIL '{{expiration}}'; 
      GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}";
 
- !layer
 
- !permit
  resources: !webservice psql-credentials
  privileges: [ read, execute ]
  role: !layer
```

#### Workflow

1. The **requester** authenticates to Conjur using their user or host credentials

2. The **requestor** asks the PostgreSQL credential factory for a new database user
    ```
    GET https://conjur.myorg.net/secrets/cucumber/webservice/psql
   ```
3. Conjur generates a new random username and password combination and connects to the database using the configured credentials to create a new user.

4. Conjur returns the new credentials to the **requester**
    ```
    {
        "id": "cucumber:variable:cucumber/webservice/psql/C3hg25bCS3",
        "user": "C3hg25bCS3",
        "password": "a85-wPLyFs6zvBMZ5ZS^"
    }
    ```

5. The **requester** uses the username/password to connect to the database.

6. Either when the TTL expires or the **requester** uses the Conjur API, Conjur connects to the database and drops the dynamic user.

---

#### Routing HTTP Verb
Credential factories are intended to be used very similarly to variables in fetching the secret value. Because of this, the secret generation and returning is currently specified as using the `GET` route for secrets. Because this is generating and creating a new secret, it may be better to use the `POST` route to generate the secret, and then use the GET to fetch its value.

---

## Resources:
- https://github.com/cyberark/conjur/compare/feature/credential-factory
