### ISSUE TITLE
Conjur supports authentication through OpenID Connect

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#660]
### Context
An OpenID connect protocol (OIDC) authenticator is a new Authenticator which implement OpenID connect protocol to authenticate users agains Okta as an OIDC provider.
The user will first get an authorization code from Okta (as OIDC provider) after successful login.
With this OIDC  authorization code the user will access to Conjur by REST to Login and Authenticate by the OIDC authenticator.

### Value
What is the benefit Open ID authenticator ?

- To authenticate human access by REST calls with OIDC on Conjur v5 
- To support multi-factor authentication (MFA) workflows through the Okta integration
- To support SSO workflow through OIDC implementation 

### Feature Demo
To demonstrate the process of authenticating to Conjur through an OpenID Connect server, we'll setup Conjur and an OpenID Connect server (with a user). We'll then authenticate using the user's OpenID Connect credentials, and retrieve a secret stored in Conjur.

### Setup
**Configuration** 
1. IT\Infosec registers the Conjur application with Okta to obtain a client ID, client secret and org. Described [here](https://developer.okta.com/blog/2018/05/18/node-authentication-with-passport-and-oidc).  
2. IT\Infosec enrolls some of the users to use different factors if at all, described [here](https://developer.okta.com/use_cases/mfa/).  

**Set up the Okta authenticator in Conjur** 
 
3. Conjur admin\Infosec adds the identity provider (Okta) URL to Conjur policy with client ID, client secret, and org as variables.  

```yml
- !policy 
  id: conjur/authn-openidconnect/okta/
  body:
    - !webservice
        annotations:
 	  description: Authentication service forOkta, based on Open ID Connect.

    - !variable
      id: clientID #value for example: DiscoveryConjurUS 

    - !variable
      id: org #value for example: Discovery 
 	
    - !variable
      id: clientsecret 
 	 
    - !group 
      id: okta-users 
        annotations:
 	  description:  
          Roles authorized to use the authn-openidconnect 
          webservice. Usually has a layer member which contains  
          enrolled applications. 

    - !permit 
      resource: !webservice 
      privilege:  read, authenticate ]  
      role:  !group okta-users
```

4. Add LDAP-conjur users to the okta-users group  
5. Enable the authn-openidconnect authenticator by setting the CONJUR_AUTHENTICATORS environment variable. For example: CONJUR_AUTHENTICATORS=authn-openidconnect/okta  

### HIGH LEVEL DESIGN

[Rest authenticator OKTA integration sequence diagram flow.pdf](https://github.com/cyberark/conjur/files/2307161/Rest.authenticator.OKTA.integration.sequence.diagram.flow.pdf)

#### Login Request
Any user that has an OIDC authorization code from Okta will perform a Login request to OIDC authenticator.

##### API Specification
`GET /authn-oidc/<service-id>/<account>/login`

##### Headers 

Key | Value 
-- | -- 
Accept | application/json

##### Request Body 

Key | Description
-- | -- 
redirect_uri | The callback URI that used to get this code
Code | OIDC authorization code

##### Response Codes
Code | Description
-- | --
200 | Returns JSON which contains the user name that login the expiration duration of the ID token and the api_key_oidc 
401 | The login Failed

###### Response (200) Example
```
{
  “user_name”: "alice",
  “expiration_duration”: “60”,
  “api_key_oidc”: "14m9cf91wfsesv1kkhevg12cdywm2wvqy6s8sk53z1ngtazp1t9tykc"
}
```

#### Authenticate Request
Any user that has an api_key_oidc from Conjur can authenticate against OIDC authenticator in order to get Conjur access token.

##### API Specification
`POST /authn-oidc/<service-id>/<account>/<user-name>/authenticate`

##### Headers 

Key | Value 
-- | -- 
Content-Type | text/plain

##### Request Body 
Content | Example | Description 
-- | -- | --
api_key_oidc | 14m9cf91wfsesv1kkhevg12cdywm2wvqy6s8sk53z1ngtazp1t9tykc | is equivalent to api key but restricted to authenticate against OIDC authenticator

##### Response Codes
Code | Description
-- | --
200 | Returns JSON which contains Conjur access token 
401 | The authenticate Failed

**Comment by nessiLahav** [comment]
### Context
An OpenID connect protocol (OIDC) authenticator is a new Authenticator which implement OpenID connect protocol to authenticate users agains Okta as an OIDC provider.
The user will first get an authorization code from Okta (as OIDC provider) after successful login.
With this OIDC  authorization code the user will access to Conjur by REST to Login and Authenticate by the OIDC authenticator.

### Value
What is the benefit Open ID authenticator ?

- To authenticate human access by REST calls with OIDC on Conjur v5 
- To support multi-factor authentication (MFA) workflows through the Okta integration
- To support SSO workflow through OIDC implementation 


### Feature Demo
To demonstrate successful authentication process through OIDC authenticator. We will demonstrate the following steps:
1. The user will get an OIDC authorization code from Okta (by REST or copied)
2. The user will send a REST login request to the Open D authenticator with the Open D authorization code to get an API_KEY_OIDC
3. The user will send a REST authenticate request to the OIDC authenticator with API_KEY_OIDC in order to get Conjur Access Token
4. The user will use Conjur Access Token to perform actions against Conjur

### Setup
**Configuration** 
1. IT\Infosec registers the Conjur application with Okta to obtain a client ID, client secret and org. Described [here](https://developer.okta.com/blog/2018/05/18/node-authentication-with-passport-and-oidc).  
2. IT\Infosec enrolls some of the users to use different factors if at all, described [here](https://developer.okta.com/use_cases/mfa/).  

**Set up the Okta authenticator in Conjur** 
 
3. Conjur admin\Infosec adds the identity provider (Okta) URL to Conjur policy with client ID, client secret, and org as variables.  

```
- !policy 
  id: conjur/<service-id>/ca
  body:
    # Signed certificates will be valid for up to a year
    - !webservice
        annotations:
          ca/intermediate-private-key: ops/ca/private-key
          ca/intermediate-certificate-chain: ops/ca/private-key-chain
          ca/max_ttl: P1M

    - !group clients

    # Allow hosts in the `clients` group to be signed 
    - !permit
      role: !group clients
      privilege: [ sign ]
      resource: !webservice
```

4. Add LDAP-conjur users to the okta-users group  
5. Enable the authn-openidconnect authenticator by setting the CONJUR_AUTHENTICATORS environment variable. For example: CONJUR_AUTHENTICATORS=authn-openidconnect/okta  

### HIGH LEVEL DESIGN

[Rest authenticator OKTA integration sequence diagram flow.pdf](https://github.com/cyberark/conjur/files/2307161/Rest.authenticator.OKTA.integration.sequence.diagram.flow.pdf)


#### Login Request
Any user that has an OIDC authorization code from Okta will perform a Login request to OIDC authenticator.

##### API Specification
`GET /authn-oidc/<service-id>/<account>/login`

##### Headers 

Key | Value 
-- | -- 
Accept | application/json

##### Request Body 

Key | Description
-- | -- 
redirect_uri | The callback URI that used to get this code
Code | OIDC authorization code

##### Response Codes
Code | Description
-- | --
200 | Returns JSON which contains the user name that login the expiration duration of the ID token and the api_key_oidc 
401 | The login Failed

###### Response (200) Example
```
{
  “user_name”: "alice",
  “expiration_duration”: “60”,
  “api_key_oidc”: "14m9cf91wfsesv1kkhevg12cdywm2wvqy6s8sk53z1ngtazp1t9tykc"
}
```

#### Authenticate Request
Any user that has an api_key_oidc from Conjur can authenticate against OIDC authenticator in order to get Conjur access token.

##### API Specification
`POST /authn-oidc/<service-id>/<account>/<user-name>/authenticate`

##### Headers 

Key | Value 
-- | -- 
Content-Type | text/plain

##### Request Body 
Content | Example | Description 
-- | -- | --
api_key_oidc | 14m9cf91wfsesv1kkhevg12cdywm2wvqy6s8sk53z1ngtazp1t9tykc | is equivalent to api key but restricted to authenticate against OIDC authenticator

##### Response Codes
Code | Description
-- | --
200 | Returns JSON which contains Conjur access token 
401 | The authenticate Failed

**Comment by jvanderhoof** [comment]
Looks like the policy was copied from the CA epic. WeCan we update that to reflect the desired policy? For the CA work, we used webservice attributes to hold variable paths.  Something like this:
```yml
- !policy 
  id: conjur/authn-openid_connect/okta
  body:
    - !webservice
        annotations:
          credential/client-id: ops/okta/client-id
          credential/client-secret: ops/okta/client-secret
          credential/organization: ops/okta/org
          credential/url: ops/okta/url

    - !group clients

    # Allow hosts in the `clients` group to be signed 
    - !permit
      role: !group clients
      privilege: [ sign ]
      resource: !webservice
```
