### ISSUE TITLE
Error during policy load

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#724]
Loading the policy:
```yaml
---
- !policy
  id: myapp
  body:
    - !policy
      id: alfa--5b43635b-2624-492b-9734-eedaa5e26655
      body:
        # Secret Declarations
        - &secrets
          - !variable hydrogen--969483f4-edbf-46fa-9198-4ac03d315e4b
          - !variable lithium--50a30dda-fbf6-4e6d-a6e4-c74ad3d50b6b
          - !variable sodium--0f443f50-c353-4cbe-b6bf-cd8cff45bf4d
          - !variable potassium--af0be0d4-e72b-454c-8e86-c48e1a2c0880
          - !variable rubidium--ce894844-f933-4a0f-8dd0-52694d3716eb
          - !variable caesium--34d71e8c-6540-4d31-9383-0bcfa1d2ca89
          - !variable francium--88bb85f2-1b67-45f0-8c84-1b278ccb61e7
          - !variable hydrogen--82244e9b-bf4b-4191-b153-9d9b614ad9d3
          - !variable lithium--d10edd73-3352-47b9-9237-3e901ebed8f2
          - !variable sodium--b6e30c8f-6886-4ab2-af0a-9c25652e8c00
          - !variable potassium--7b797ad2-a25f-48b8-a41e-fe27b1f24fd6
          - !variable rubidium--34611208-353a-4677-8353-686783d9fd69
          - !variable caesium--cad5d00f-8936-4072-b431-fe1857ab0a70
        
        # User & Manager Groups
        - !group secrets-users
        - !group secrets-managers
        - !permit
          role: !group secrets-users
          privileges: [ read, execute ]
          resources: *secrets
        - !permit
          role: !group secrets-managers
          privileges: [ read, execute, update ]
          resources: *secrets
    
    # === Layer for Automated Secret Access ===
    - !policy
      id: hosts
      annotations:
        description: Layer & Host Factory for machines that can read secrets
      body:
        - !layer
        - !host-factory
    - !grant
      role: !group alfa--5b43635b-2624-492b-9734-eedaa5e26655/secrets-users
      member: !layer hosts
```

Produces the error message in the log:
```
I, [2018-08-30T14:23:46.292990 #2435]  INFO -- : Completed 500 Internal Server Error in 91ms
F, [2018-08-30T14:23:46.293752 #2435] FATAL -- :
NoMethodError (undefined method `map' for nil:NilClass):
  app/models/loader/types.rb:152:in `layer_roleids'
  app/models/loader/types.rb:140:in `create!'
  app/models/loader/orchestrate.rb:283:in `map'
  app/models/loader/orchestrate.rb:283:in `load_records'
  app/models/loader/orchestrate.rb:87:in `load'
  app/controllers/policies_controller.rb:42:in `load_policy'
  app/controllers/policies_controller.rb:15:in `put'
  app/controllers/application_controller.rb:39:in `block in run_with_transaction'
  app/controllers/application_controller.rb:38:in `run_with_transaction'
  lib/rack/remember_uuid.rb:12:in `call'
```
