### ISSUE TITLE
Rotation happens immediately, instead of waiting for the first TTL to pass

### ISSUE THREAD

**Issue by apotterri** [cyberark/conjur#742]
Once it's possible for a rotation to succeed, it happens immediately, rather than waiting for the first TTL to expire. This makes it very hard to use.

For example, say I create a Postgres user, and generate a password for it, and set it as the user's password. In some circumstances (e.g. the Terraform provider), I need the password to retain that value until my application has connected to the database as that user.

However, if I subsequently load the policy
```
- !policy
  id: app/db
  body:
    - !variable
       id: password
          annotations:
            rotation/rotator: postgresql/password
            rotation/ttl: P1Y
            rotation/postgresql/password/length: 32
    - !variable url
    - !variable username
```

and add values for each of `app/db/password`, `app/db/url`, and `app/db/username`, the value of `app/db/password` gets rotated immediately, and my app fails to start.
