### ISSUE TITLE
Creating a host-factory slightly wrong yields a 500 error

### ISSUE THREAD

**Issue by ryanprior** [cyberark/conjur#743]
Creating a host-factory with a "layer" instead of "layers" chokes the service.

#### Steps to reproduce
1. log in to Conjur as admin
1. load this policy at `root`:
```yaml
- !policy
  id: hostfactory-broken
  body:
    - !layer
    - !host-factory
      layer: !layer
```

Expected result: a layer & hostfactory
Disappointing but valid alternate result: error to the effect of "a host-factory must have a `layers` attribute
Actual result: 500 error

#### Workaround
This alternate policy works as expected:
```yaml
- !policy
  id: hostfactory-not-broken
  body:
    - !layer
    - !host-factory
      layers: [ !layer ]
```
