### ISSUE TITLE
authn-k8s can't authenticate pods controlled by DeploymentConfig

### ISSUE THREAD

**Issue by rafis3** [cyberark/conjur#793]
This bug needs to be reverified.
The Conjur authn-k8s might not be able to authenticate pods that were created by a DeploymentConfig. The reason is that Conjur lacks permissions to query the K8s API on this type of resource.
The suggested fix should look like this:
```
---
apiVersion: v1
kind: ClusterRole
metadata:
  name: conjur-authenticator-conjur
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "serviceaccounts","deploymentconfigs", "replicationcontrollers" ]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: [ "deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]  # needed on OpenShift 3.7+
  resources: [ "deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
```
We need to make sure this role can be uploaded into Kubernetes as well, not just OpenShift. Otherwise, we will need to create two versions of this manifest.
