### ISSUE TITLE
Host Factory and layer require the same ID

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#826]
**Current Behavior**
When creating a host factory for a layer, the host factory and the layer require the same ID:
Doesn't work = the 'new token' option disappears from host factory table
```
### WORKS no ID given to host-factory or layer
- !policy
  id: test
  body:
  - !host-factory
    layer: [ !layer ] 

  - !layer
 

### DOESN'T WORK same ID given to policy and host-factory
- !policy
  id: test
  body:
  - !host-factory
    id: test
    layer: [ !layer ] 

  - !layer
 
### DOESN'T WORK
- !policy
  id: test
  body:
  - !host-factory
    id: test
    layer: [ !layer ] 

  - !layer
    id: test_layer
 
### WORKS host-factory and layer ID are same
- !policy
  id: test
  body:
  - !host-factory
    id: test_layer
    layer: [ !layer ] 

  - !layer
    id: test_layer
```
**Expected Behavior**
Layer and host factory can have unique IDs.
